### ISSUE TITLE
Collection of todos for version 0.4.4

### ISSUE THREAD

**Issue by retostauffer** [retostauffer/python-colorspace#13]
This issue is intended to be modified by the developers (@retostauffer, @zeileis). Lists some of the todos for the next version (version 0.4.4).

## Todo

* [x] [`specplot`](https://retostauffer.github.io/python-colorspace/man/colorspace.specplot.specplot.html) Examples: Not showing what they intend to show (wrong palette, arguments not recognized; Reto)
* [x] [`sequential_hcl`](colorspace.palettes.sequential_hcl.html) and other palettes: Argument `c` can be a vector, so far Python colorspace expected `[c1, c2, cmax]`. Will be adjusted (wip).
    - [x] `sequential_hcl()` works
    - [x] `choose_palette()` had some issues, working on it
    - [x] `choose_palette()` tested; works for all except the next item ....
* [x] GUI fails when using `Basic Qualitative; debug and fix.
* [x] `hclplot` (for now in devel branch): Plot for `"qualitative"` palettes must be added (Reto, #9).
* [x] `hclplot`: Slightly differs from the _R_ version (tbd.) and must be tested more rigorously (Reto, see #9).
    - [x] Issue with `hclplot(qualitative_hcl("Dynamic"));` (see https://github.com/retostauffer/python-colorspace/issues/9#issuecomment-2155393835)
* [x] Discuss if we should allow GPL3+ and GPL2+ (see #12), adjust `setup.py` accordingly (Reto).
* [x] Think of adding a dedicated article on how to use `colorspace` with `matplotlib`, currently we have a short section in [Getting started](https://retostauffer.github.io/python-colorspace/getstarted.html#use-with-matplotlib-graphics) (Reto).
* ~ `seaborn` uses an object `seaborn.palettes._ColorPalette` for handling (custom) color palettes which are created from a list of colors. `colorspace` palettes can easily be converted (Reto).~ (postponed)
    -  [x] Required: Having a dedicated article or short section on how to do so.
     - ~Check: brewer palettes only provide `<= N` colors from original palette~ (postponed)
    - ~Check: has its own `color_palette()` method (check)~ (postponed)
    - ~Check: has its own `diverging_palette()` function making a diverging palette between two HUSL colors~ (postponed)
    - [x] Check: integrates matplotlib cmaps (linearely interpolated)
    - ~Are `sns.color_palettes()` more precise than cmaps? Or interchangeable (if so, we have the solution already).~ (postponed)
* [x] `plotly`: Dedicated article or section on how to use `colorspace` with ploty (Reto).
* [x] `qualitative_hcl` still using the default `h = [0, 360]` (see [demos for qualitative colors](https://retostauffer.github.io/python-colorspace/articles/palette_visualization.html#trajectories-in-hcl-space)). We have already addressed this issue in [`rainbow`](https://retostauffer.github.io/python-colorspace/man/colorspace.palettes.rainbow.html) and [`rainbow_hcl`](https://retostauffer.github.io/python-colorspace/man/colorspace.palettes.rainbow_hcl.html) by adding a lambda function for the `end` argument; must be added to `qualitative_hcl` as well (Reto).
   -  [x] Done, allowing for lambda functions with two arguments (`n`, `h1`) to properly calculate lower/upper limits for `h` for the qualitative palettes which need them. Adjusted the `*.conf` files; updated `palette.colors()` method.
   - [x] lambda functions: Update documentation and properly describe these arguments somewhere (Reto).
 * [x] Check (and extend) conversion from/to HSV/HLS.

**Comment by retostauffer** [comment]
I will close this issue in a second, most of the open todos are done or postponed.

**Additional changes:** Added articles for `seaborn`, `plotly` and `matplotlib`. These _are not yet finished_ (moving it to the next issue). In addition, a `dataset()` function was added for handling the example data (for now there is volcano, HarzTraffic and MonthlyHarzTraffic (based on HarzTraffic; currently unused). The "HCL-Based Plaettes for xxx` will be extended these days (see new issue).

I have, just now, disabled testing for Python 3.7 (EOL last year; problems installing `pandas` required for the datasets). 

**Done:** Series of bugfixes, extensions, and testing.

**Postponed:** Implementing special methods and classes of seaborn color palettes as they (to my knowledge) are not needed, at least for now.
