### ISSUE TITLE
Collection of todos for version 0.4.4

### ISSUE THREAD

**Issue by retostauffer** [retostauffer/python-colorspace#15]
New todo list for the devs (@zeileis @retostauffer). This is a follow up for #13 .

## Todo

* [x] Articles for 'HCL-Based Palettes for seaborn'
   * [x] Double-check
   * [x] Add barplot based on 'MonthlyHarzTraffic'?
* [x] Articles for 'HCL-Based Palettes for plotly'
   * [x] Double-check and update/extend
* [x] Articles for 'HCL-Based Palettes for matplotlib
   * [x] Revamp
* "Getting started"
   * [x] Update section, I've just thrown some examples in there
* GitHub CI
   * ~~Any easy way to run tests for 3.7 without `pandas` (`dataset()`)?~~ EOL 2023, removed
   * [x] Add 'versions tested' to `installation.qmd`
* [x] `installation`: Add that `pandas` is needed for some datasets
* [x] Allow `ListedColormap`s for `specplot()` and `cmap.cmap_to_sRGB` to visualize maps from third party packages.

**Comment by retostauffer** [comment]
Just released version `0.4.4` on PyPI, closing this issue.

**Comment by retostauffer** [comment]
...
