### ISSUE TITLE
Internal ToDo

### ISSUE THREAD

**Issue by retostauffer** [retostauffer/python-colorspace#20]
As discussed today, two things have to be done if possible.

*  [x] Rename `cvd_emulator` to `cvd_image` to be consistent with _R_ colorspace.
    * [x] `src/colorspace`
    * [x] Tests (if needed)
    * [x] `_quarto` references; delete no longer required `_quarto/man/*` pages
* [x] Alpha handling:
   * [x] `diverging_hcl`
   * [x] `sequential_hcl`
   * [x] `qualitative_hcl`
   * [x] `divergingx_hcl`
   * [x] `rainbow_hcl`
   * [x] `rainbow`
   * [x] `heat_hcl`
   * [x] `terrain_hcl`
   * [x] `diverging_hsv`
* [x] Error when drawing one color from `diverging_hcl` and `divergingx_hcl`; add fix we implemented yesterday in R `2.1-1`.
* [x] Differences R/Py
    * [x] Check/fix `diverging_hsv`
    * [x] Check/fix `divergingx_hcl`
